### PR TITLE
Plot tools from settings file

### PR DESCRIPTION
**Pull request by RobSalati**
Functions for every tool to auto generate plots when given a settings file.

### CODE REVIEW

**Comment by RobSalati** [comment]
This branch has:
Functions to generate plots for each tool from a settings file
A new function to plot two sets of mtp muscle model parameters on the same plot
New colors for every plot :)
A function to plot joint velocities in treatment optimization

**Comment by SpencerTWilliams** [comment]
The TO plotting function will crash if the results directory does not have GRFData. This should be an optional plot that is skipped if the directory doesn't exist.

**Comment by RobSalati** [comment]
GRF plots now have a conditional attached to them.

I also added velocity plots to be automatically generated, and fixed an issue with MTP plotting.

**Review by SpencerTWilliams — APPROVED** [review]
Fixed a file path bug in GCP and a weird Matlab indexing issue in JMP. Ready to merge now.

**Pull request merged**
