### PR TITLE
Added free final time formulation

### PR DESCRIPTION
**Pull request by MarlenyVega**

### CODE REVIEW

**Review by SpencerTWilliams — APPROVED** [review]

**Comment by cvhammond** [comment]
`TrackingOptimization/ToyArmExample` in `nmsm-example` doesn't converge for `FreeFinalTime` branch and `nmsm-test` branch `dev` doesn't pass.

**Comment by MarlenyVega** [comment]
@cvhammond all tests on my side are fixed except one called "testParseData", please take a look at the pull request in the nmsm-test repository.

**Comment by cvhammond** [comment]
ok I see that testParseData is the only failing test. Have you tried the Treatment Optimization Toy Example? On `dev` it converges in 7 iterations, but on FreeFinalTime it doesn't resolve.

**Comment by MarlenyVega** [comment]
It should now be fixed! The free final time converged in 132 iterations.

**Comment by cvhammond** [comment]
I am on nmsm-core branch FreeFinalTime and branch main for nmsm-examples and in the TrackingOptimization directory of nmsm-examples, in the ToyArmExample, the script TOToyExample.m runs but does not resolve to a value. I stopped it after 3000 function iterations. Do you mind looking at that? The VO and DO examples run as expected.

**Comment by MarlenyVega** [comment]
Ah, I see. I didn't check the toy arm example for the tracking optimization. I'll take a look!

**Comment by MarlenyVega** [comment]
The toy example works for all three tools now!

**Review by cvhammond — APPROVED** [review]
Looks good! Thanks for making those changes to get the Toy Arm Examples working

**Pull request merged**
