### PR TITLE
Allow absolute changes to length parameters in Length Initialization, update element name

### PR DESCRIPTION
**Pull request by SpencerTWilliams**
These changes are mainly to support optimizing absolute length parameters instead of optimal fiber length and tendon slack length scale factors. Users will use the cost terms "optimal_fiber_length" and "tendon_slack_length" in either case, and the software will automatically choose which cost term to use (scale factor or absolute deviation) based on the `<optimize_absolute_length_changes>` setting. 

Because of the difference in scale, recommended allowable errors for the cost term will be different depending on whether scale factors or absolute values are being optimized. The `<error_center>` element should also be set to 0 for absolute changes and 1 for scale factors.

This branch also renames the `<optimize_isometric_max_force>` element to `<update_maximum_isometric_force>` for clarity, since the max isometric force is not optimized directly. 

These features require changes to XML settings files, so these updates should not be merged into main until version 1.1. The following block should be added to `<MuscleTendonLengthInitialization>` blocks in settings files, with the `<optimize_isometric_max_force>` elements removed: 

``` xml
<!-- Boolean (true, false) indicating whether maximum isometric force should be updated for muscles based on changes to muscle stress and length parameters. Default is true.-->
<update_maximum_isometric_force>true</update_maximum_isometric_force>
<!--*Optional* Boolean (true, false) indicating whether absolute value changes in length parameters will be optimized instead of using scale factors. Default is false.-->
<optimize_absolute_length_changes>true</optimize_absolute_length_changes>
```

### CODE REVIEW

**Comment by SpencerTWilliams** [comment]
Closes #247 
Closes #258

**Comment by cvhammond** [comment]
the only thing we need to do for this is try out the tutorial step for NCP to see if it makes pre-cal easier

**Comment by SpencerTWilliams** [comment]
Remaining to merge this: 
- Update to current dev
- Make either `<optimize_isometric_max_force>` or `<update_maximum_isometric_force>` acceptable so examples still work
- Make `<optimize_absolute_length_changes>` an optional element

**Comment by SpencerTWilliams** [comment]
Will close #257 since tutorial works as expected

**Comment by SpencerTWilliams** [comment]
This can be safely merged after debug-synergy-driven and acceleration-controls.

**Pull request merged**
