### PR TITLE
Adding treatment optimization cost functions

### PR DESCRIPTION
**Pull request by MarlenyVega**

### CODE REVIEW

**Comment by cvhammond** [comment]
@MarlenyVega please look at my last commit, a few small changes to allow ToyArm examples to pass, if it's fine then I'll merge in

**Comment by MarlenyVega** [comment]
@cvhammond everything looks great!

**Comment by MarlenyVega** [comment]
@cvhammond I think all function descriptions have been updated for treatment optimization! This branch should be good to go.

**Comment by MarlenyVega** [comment]
@cvhammond Can you please run the toy arm example for tracking optimization and let me know what you think about the initial guess checking?

**Review by cvhammond — APPROVED** [review]

**Pull request merged**
